services:
  metabase:
    image: metabase/metabase:v0.49.11
    ports:
      - "3000:3000"
    networks:
      - metabase
      - terrarium
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

networks:
  metabase:
  terrarium:
    name: terrarium
