services:
  metabase:
    image: metabase/metabase:v0.49.11
    ports:
      - "3000:3000"
    networks:
      - metabase
      - terrarium
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    networks:
      - metabase

networks:
  metabase:
  terrarium:
    name: terrarium
