pages:
  stage: deploy
  image: python:3.11-slim
  script:
    - pip install poetry
    - poetry install --only docs
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
