pages:
  stage: deploy
  image: python:3.11-slim
  script:
    - pip install mkdocs-material
    - cp -rf README.md docs/index.md
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'