site_name: Tech-Terrarium Docs
site_url: https://foehammer82.github.io/tech-terrarium/
repo_url: https://github.com/Foehammer82/tech-terrarium

nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - Services:
      - Data Catalog:
          - services/datahub.md
          - services/openmetadata.md
          - services/alternative_data_catalogs.md
      - Data Store:
          - services/kafka.md
          - services/postgres.md
          - services/mongodb.md
          - services/spark.md
      - Application Framework:
          - services/fastapi_app.md
      - Orchestration & ETL/ELT:
          - services/airflow.md
          - services/dbt.md
      - Machine Learning:
          - services/feast.md
          - services/mlflow.md
      - BI & Analytics:
          - services/metabase.md
      - services/scrubbed_services.md
      - ... | services/*
  - ... | examples/*
  - ... | notes/*

theme:
  name: material
  logo: assets/terrarium.png
  features:
    - toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections # flat is better than nested
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.tracking
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter