services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8084:8000"
    networks:
      - terrarium
    environment:
      PUID: 1001
      PGID: 1001
