- Administration:
    - Portainer:
        icon: portainer
        href: https://localhost:8443/
        siteMonitor: https://localhost:8443/
    - InfluxDB:
        icon: influxdb
        href: http://apollo:8086/
    - Docs:
        icon: mkdocs
        href: https://docs.dark-water.net/

- Services:
    - Kafka Admin (Kafbat-UI):
        icon: kafka
        href: http://kronos.secure:3030/
    - Postgres Admin (pgAdmin):
        icon: postgres
        href: http://kronos.secure:5050/

