---
- Bookmarks:
    - Gitlab Repo:
        - icon: gitlab
          href: https://gitlab.com/Foehammer82/tech-terrarium
    - Github Repo (gitlab-mirrored):
        - icon: github
          href: https://github.com/Foehammer82/tech-terrarium
