- Admin:
    - MkDocs:
        icon: /images/mkdocs-material.png
        description: Documentation for the Tech-Terrarium
        href: https://tech-terrarium.foehammer.dev/
        siteMonitor: https://tech-terrarium.foehammer.dev/
    - Portainer:
        icon: portainer
        description: Manage your Docker environment
        href: https://localhost:8443/
        container: admin-portainer-1
    - Glances:
        icon: glances
        description: System stats monitoring
        href: http://localhost:61208/
        container: admin-glances-1

- Data Stores:
    - Kafka (Kafbat-UI):
        icon: /images/kafka_icon.png
        href: http://localhost:9021/
        container: kafka-kafbat-ui-1
    - Postgres (pgAdmin):
        icon: postgres
        href: http://localhost:5050/
        container: postgres-pgadmin-1
    - MongoDB (Mongo-Express):
        icon: mongodb
        href: http://localhost:8086/
        container: mongo-mongo-express-1
    - Redis (Redis-Commander):
        icon: redis
        href: http://localhost:8085/
        container: redis-redis-commander-1
    - Spark:
        icon: /images/spark_icon.png
        description: NOT IMPLEMENTED YET

- Application Frameworks:
    - FastAPI App (Swagger Docs):
        icon: /images/fastapi_icon.svg
        href: http://localhost:8084/
    - FastAPI App (Admin):
          icon: /images/fastapi_icon.svg
          href: http://localhost:8084/
          description: NOT IMPLEMENTED YET

- Orchestration:
    - Airflow:
        icon: /images/airflow_icon.png
        description: "username: airflow \npassword:airflow"
        href: http://localhost:8080/
        container: airflow-airflow-webserver-1

- ETL/ELT:
    - DBT:
        icon: /images/dbt_icon.png
        description: NOT IMPLEMENTED YET

- Machine Learning:
    - Feast:
        icon: /images/feast_icon.png
        description: NOT IMPLEMENTED YET
    - MlFlow:
        icon: /images/mlflow_icon.png
        description: NOT IMPLEMENTED YET

- BI Tools & Data-Cataloging:
    - Datahub:
        icon: /images/datahub_icon.png
        description: NOT IMPLEMENTED YET
    - Metabase:
        icon: metabase
        href: http://localhost:3000
        container: metabase-metabase-1
