- Admin:
    - MkDocs:
        icon: /images/mkdocs-material.png
        description: Documentation for the Tech-Terrarium
        href: https://foehammer82.github.io/tech-terrarium/
        siteMonitor: https://foehammer82.github.io/tech-terrarium/
    - Portainer:
        icon: portainer
        description: "WebUI for Docker Administration"
        href: https://localhost:8443/
        container: admin-portainer-1
    - Glances:
        icon: glances
        description: System stats monitoring
        href: http://localhost:61208/
        container: admin-glances-1

- Data Stores:
    - Kafka (Kafbat-UI):
        icon: /images/kafka_icon.png
        href: http://localhost:9021/
        description: "un/pw: NONE"
        container: kafka-kafbat-ui-1
    - Postgres (pgAdmin):
        icon: postgres
        href: http://localhost:8888/
        description: "un/pw: admin@not.com/password"
        container: postgres-pgadmin-1
    - MongoDB (Mongo-Express):
        icon: mongodb
        href: http://localhost:8086/
        description: "un/pw: admin/password"
        container: mongo-mongo-express-1
    - Redis (Redis-Commander):
        icon: redis
        href: http://localhost:8085/
        description: "un/pw: NONE"
        container: redis-redis-commander-1
    - Spark:
        icon: /images/spark_icon.png
        description: "NOT IMPLEMENTED YET"

- Application Frameworks:
    - FastAPI App (Swagger Docs):
        icon: /images/fastapi_icon.svg
        href: http://localhost:8084/
    - FastAPI App (Admin):
          icon: /images/fastapi_icon.svg
          href: http://localhost:8084/
          description: NOT IMPLEMENTED YET

- Orchestration:
    - Airflow:
        icon: /images/airflow_icon.png
        description: "un/pw: airflow/airflow"
        href: http://localhost:8080/
        container: airflow-airflow-webserver-1

- Machine Learning:
    - Feast:
        icon: /images/feast_icon.png
        description: NOT IMPLEMENTED YET
    - MlFlow:
        icon: /images/mlflow_icon.png
        description: NOT IMPLEMENTED YET

- BI Tools & Data-Cataloging:
    - Datahub:
        icon: /images/datahub_icon.png
        description: "un/pw: datahub/datahub"
        href: http://localhost:9002/
        container: datahub-frontend-1
    - Metabase:
        icon: metabase
        href: http://localhost:3000
        description: "un/pw: admin@not.com/1terrarium"
        container: metabase-metabase-1
