title: Tech-Terrarium
background:
  image: /images/terrarium_bg.png
  opacity: 60
favicon: /images/favicon.ico
cardBlur: sm
theme: dark
color: slate
hideVersion: true
headerStyle: clean
showStats: true
fiveColumns: true
disableCollapse: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

layout:
  Admin:
    style: "row"
    columns: 4
    useEqualHeights: true
    disableCollapse: true

  Data Stores:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
  Application Frameworks:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
  Orchestration & ETL/ELT:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
  ETL/ELT:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
  Machine Learning:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
  BI Tools & Data-Cataloging:
    style: "columns"
    useEqualHeights: true
    disableCollapse: true
