title: Tech-Terrarium
background:
  image: /images/terrarium_bg.png
  opacity: 60
favicon: /images/favicon.png
cardBlur: sm
theme: dark
color: slate
hideVersion: true
headerStyle: clean
showStats: false

layout:
  Admin:
    style: "row"
    columns: 3
    useEqualHeights: true
    disableCollapse: true
  Services:
    style: "row"
    columns: 4
    useEqualHeights: true
    disableCollapse: true
