services:
  homepage:
    build:
      context: homepage
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - admin
      - terrarium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only

  glances:
    image: nicolargo/glances:latest-alpine
    restart: on-failure
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "--webserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - admin

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
#      - "8000:8000"
      - "8443:9443"
    networks:
      - admin

networks:
  admin:
  terrarium:
    name: terrarium

volumes:
  portainer-data:
