services:
  homepage:
    build:
      context: homepage
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - admin
      - terrarium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only

  glances:
    image: nicolargo/glances:latest-alpine
    restart: on-failure
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "--webserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - admin

networks:
  admin:
  terrarium:
    name: terrarium

volumes:
  uptime-kuma-data:
