services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: trino
    restart: on-failure
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - ./catalog:/etc/trino/catalog
