services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: trino
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - terrarium
    volumes:
      - ./catalog:/etc/trino/catalog

networks:
  terrarium:
    name: terrarium
