services:
  db:
    image: postgres:15
    restart: on-failure
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - terrarium
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    ports:
      - "8888:80"
    networks:
      - terrarium
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@not.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data:

networks:
  terrarium:
    name: terrarium
