services:
  db:
    image: mongo:7
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo
      - terrarium
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - ./mongo_init/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express:latest
    restart: on-failure
    ports:
      - "8086:8081"
    networks:
      - mongo
      - terrarium
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - db

volumes:
  mongo-data:

networks:
  mongo:
  terrarium:
    name: terrarium
