services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis
      - terrarium
    volumes:
      - redis-data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: on-failure
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8085:8081"
    networks:
      - redis
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  redis:
  terrarium:
    name: terrarium